;-------------------------------------------------------------
; 2. AddVariables Program
; Modify the AddVariables program so it uses 64-bit variables. 
; Describe the syntax errors generated by the assembler and 
; what steps you took to resolve the errors
;-------------------------------------------------------------

section .data
    ; 64-bit variables (QWORD instead of DWORD)
    var1 QWORD 10000000000     ; 
    var2 QWORD 20000000000     ; 
    sum  QWORD 0               ; Result variable

section .text
global _start

_start:
    ; Add two 64-bit variables
    mov rax, [var1]           ; Load first value with usage of RAX instead of EAX
    add rax, [var2]           ; Then we add the second value
    mov [sum], rax            ; And store the result
    
    ; Exit program
    mov rax, 60
    xor rdi, rdi
    syscall